apiVersion: v1
kind: Pod
metadata:
  name: django-app
  labels:
    app : webapp
spec:
  containers:
  - name: django-app
    image: cicddjangoimages.azurecr.io/samplewebapp:v3
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-lb
spec:
  selector:
    app: webapp
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
